route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            username: 'sonlinux'
            channel: '#biodiversity'
            api_url: '<incomming-webhook-url>'